language: ruby
services:
  - postgresql
before_install: gem install bundler -v 1.10.6
before_script:
  - psql -c 'create database testing;' -U postgres
rvm:
  - 2.1.7
  - 2.2.3
gemfile:
  - Gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails40.gemfile
